
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://119.23.225.124:3306/todolist
    username: yang
    password: MyNewPass4!
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB #maxFileSize 是单个文件大小
      max-request-size: 30MB #maxRequestSize是设置总上传的数据大小
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8081

#自定义的属性，指定了一个路径，注意要以/结尾
web:
  upload-path: F:/img/test2/


